#num_gpus = 1

###########################################
# NEED TO SPECIFY THE FOLLOWING VARIABLES
#
# cfg_file
# epochs
# metrics_plane
# num_gpus
# do_ddp
###########################################


executable     = /lbne/u/jcalcutt/training_condor/run_training.sh 
universe       = vanilla
output         = training.$(Cluster).$(Process).out
error          = training.$(Cluster).$(Process).err
log            = training.log
#cfg_file       = /home/dune/users/jcalcutt/wire-cell-python/wirecell/dnn/cfg/spng_campaign/jcal-dnnroi-spng-dense_input-mpfile-uplane-pdhd.cfg
#cfg_file       = /home/dune/users/jcalcutt/test.cfg 
device         = gpu
#epochs         = 100
#epochs         = 2
DO_METRICS     = 1
#metrics_plane  = u
ncores_snakemake        = 8
do_amp         = 1
do_cache = 0

environment = "HOME=/home/dune/users/jcalcutt ClusterId=$(Cluster) ProcessId=$(Process) device=$(device) epochs=$(epochs) DO_METRICS=$(DO_METRICS) ncores_snakemake=$(ncores_snakemake) metrics_plane=$(metrics_plane) cfg_file=$(cfg_file) batch=$(batch) ebatch=$(ebatch) do_amp=$(do_amp) do_cache=$(do_cache) extra_dir_name=$(extra_dir_name) seed=$(seed) do_ddp=$(do_ddp) ddp_ngpu=$(num_gpus) XVU=$(do_xvu)"

# Request the GPU resources from the slot
request_gpus   = $(num_gpus)
request_memory = 25000M
request_disk = 50G

# Define the specific hardware requirements
# We use '==' for exact string matching and '>=' or '==' for capability
Requirements = (GPUs_DeviceName == "NVIDIA L40S") && (GPUs_Capability == 8.9)

# Ensure the job is sent to the correct execution environment
should_transfer_files = NO
#when_to_transfer_output = ON_EXIT

queue 1
